### PR TITLE
WhatsApp bot

### PR DESCRIPTION
**Pull request by urmil89**

### CODE REVIEW

**Comment by urmil89** [comment]
why are you closed this plz explain

**Comment by FayasNoushad** [comment]
> why are you closed this plz explain

Please add python code in [Python](https://github.com/FayasNoushad/Python) Repository.

**Comment by FayasNoushad** [comment]
You can also contribute on [Website](https://github.com/FayasNoushad/Website) for hacktoberfest.

**Comment by urmil89** [comment]
got it brother

**Pull request closed without merging**
